#!/bin/sh

sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 empty gold1/kresponse(l31, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 empty gold2/kresponse(l31, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 empty gold1/knresponse(l31, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 empty gold2/knresponse(l31, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 strong gold1/kresponse(l31, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 strong gold2/kresponse(l31, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 strong gold1/knresponse(l31, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 strong gold2/knresponse(l31, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 weak gold1/kresponse(l31, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l31 weak gold2/kresponse(l31, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 weak gold1/knresponse(l31, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l31 weak gold2/knresponse(l31, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 empty gold1/kresponse(l21, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 strong gold1/kresponse(l21, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 weak gold1/kresponse(l21, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 empty gold2/kresponse(l21, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 strong gold2/kresponse(l21, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l21 weak gold2/kresponse(l21, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 empty gold1/knresponse(l21, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 strong gold1/knresponse(l21, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 weak gold1/knresponse(l21, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 empty gold2/knresponse(l21, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 strong gold2/knresponse(l21, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l21 weak gold2/knresponse(l21, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 empty gold1/kresponse(l32, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 strong gold1/kresponse(l32, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 weak gold1/kresponse(l32, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 empty gold2/kresponse(l32, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 strong gold2/kresponse(l32, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l32 weak gold2/kresponse(l32, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 empty gold1/knresponse(l32, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 strong gold1/knresponse(l32, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 weak gold1/knresponse(l32, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 empty gold2/knresponse(l32, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 strong gold2/knresponse(l32, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l32 weak gold2/knresponse(l32, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 empty gold1/kresponse(l11, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 strong gold1/kresponse(l11, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 weak gold1/kresponse(l11, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 empty gold2/kresponse(l11, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 strong gold2/kresponse(l11, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l11 weak gold2/kresponse(l11, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 empty gold1/knresponse(l11, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 strong gold1/knresponse(l11, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 weak gold1/knresponse(l11, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 empty gold2/knresponse(l11, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 strong gold2/knresponse(l11, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l11 weak gold2/knresponse(l11, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 empty gold1/kresponse(l22, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 strong gold1/kresponse(l22, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 weak gold1/kresponse(l22, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 empty gold2/kresponse(l22, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 strong gold2/kresponse(l22, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l22 weak gold2/kresponse(l22, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 empty gold1/knresponse(l22, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 strong gold1/knresponse(l22, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 weak gold1/knresponse(l22, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 empty gold2/knresponse(l22, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 strong gold2/knresponse(l22, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l22 weak gold2/knresponse(l22, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 empty gold1/kresponse(l33, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 strong gold1/kresponse(l33, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 weak gold1/kresponse(l33, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 empty gold2/kresponse(l33, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 strong gold2/kresponse(l33, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l33 weak gold2/kresponse(l33, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 empty gold1/knresponse(l33, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 strong gold1/knresponse(l33, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 weak gold1/knresponse(l33, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 empty gold2/knresponse(l33, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 strong gold2/knresponse(l33, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l33 weak gold2/knresponse(l33, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 empty gold1/kresponse(l12, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 strong gold1/kresponse(l12, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 weak gold1/kresponse(l12, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 empty gold2/kresponse(l12, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 strong gold2/kresponse(l12, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l12 weak gold2/kresponse(l12, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 empty gold1/knresponse(l12, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 strong gold1/knresponse(l12, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 weak gold1/knresponse(l12, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 empty gold2/knresponse(l12, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 strong gold2/knresponse(l12, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l12 weak gold2/knresponse(l12, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 empty gold1/kresponse(l23, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 strong gold1/kresponse(l23, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 weak gold1/kresponse(l23, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 empty gold2/kresponse(l23, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 strong gold2/kresponse(l23, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l23 weak gold2/kresponse(l23, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 empty gold1/knresponse(l23, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 strong gold1/knresponse(l23, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 weak gold1/knresponse(l23, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 empty gold2/knresponse(l23, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 strong gold2/knresponse(l23, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l23 weak gold2/knresponse(l23, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 empty gold1/kresponse(l13, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 strong gold1/kresponse(l13, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 weak gold1/kresponse(l13, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 empty gold2/kresponse(l13, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 strong gold2/kresponse(l13, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_0 l13 weak gold2/kresponse(l13, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 empty gold1/knresponse(l13, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 strong gold1/knresponse(l13, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 weak gold1/knresponse(l13, weak, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 empty gold2/knresponse(l13, empty, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 strong gold2/knresponse(l13, strong, gold/g' plan.dot
sed -i 's/sensor-scan__sensor__-obs0_DETDUP_1 l13 weak gold2/knresponse(l13, weak, gold/g' plan.dot

dot plan.dot -Tpng > plan.png
